services:
  # A Docker web service
  - type: web
    name: spark-app
    env: docker
    repo: https://github.com/davidandrewrice/SparkExperimentation.git # optional
    plan: starter # optional (defaults to starter)
    branch: main # optional (defaults to master)
    healthCheckPath: /ping
  - type: redis
    name: spark-redis
    plan: free
    ipAllowList: []
    region: frankfurt
